version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  webpacker:
    build: .
    env_file:
      - '.env.docker'
    command: ./bin/webpack-dev-server
    volumes:
      - .:/srv
    ports:
      - '3035:3035'

  web:
    build: .
    env_file:
      - '.env.docker'
    command: bash -c "sleep 5 && rm -f /srv/tmp/pids/server.pid && rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/srv
    ports:
      - '3000:3000'
    depends_on:
      - db
